"""Tests for nthlayer.generators.alerts — alert generation from manifests."""

from pathlib import Path

import pytest
import yaml

from nthlayer_generate.alerts import AlertRule
from nthlayer_generate.generators.alerts import (
    extract_dependencies,
    filter_by_tier,
    generate_alerts_for_service,
    write_prometheus_yaml,
)
from nthlayer_generate.specs.models import Resource


class TestExtractDependencies:
    def test_empty_resources(self):
        assert extract_dependencies([]) == []

    def test_non_dependency_resources_ignored(self):
        resources = [Resource(kind="SLO", name="avail", spec={})]
        assert extract_dependencies(resources) == []

    def test_extracts_database_type(self):
        resources = [
            Resource(
                kind="Dependencies",
                name="deps",
                spec={"databases": [{"type": "postgresql", "name": "main"}]},
            )
        ]
        deps = extract_dependencies(resources)
        assert "postgresql" in deps

    def test_infers_db_type_from_name(self):
        resources = [
            Resource(
                kind="Dependencies",
                name="deps",
                spec={"databases": [{"name": "postgres-main"}]},
            )
        ]
        deps = extract_dependencies(resources)
        assert "postgres" in deps

    def test_extracts_service_type(self):
        resources = [
            Resource(
                kind="Dependencies",
                name="deps",
                spec={"services": [{"type": "redis", "name": "cache"}]},
            )
        ]
        deps = extract_dependencies(resources)
        assert "redis" in deps

    def test_deduplicates(self):
        resources = [
            Resource(
                kind="Dependencies",
                name="deps",
                spec={
                    "databases": [
                        {"type": "postgresql", "name": "a"},
                        {"type": "postgresql", "name": "b"},
                    ]
                },
            )
        ]
        deps = extract_dependencies(resources)
        assert deps.count("postgresql") == 1


class TestFilterByTier:
    @pytest.fixture
    def sample_alerts(self):
        return [
            AlertRule(
                name="crit1",
                severity="critical",
                expr="up == 0",
                technology="test",
            ),
            AlertRule(
                name="warn1",
                severity="warning",
                expr="up < 0.5",
                technology="test",
            ),
            AlertRule(
                name="info1",
                severity="info",
                expr="up < 0.9",
                technology="test",
            ),
        ]

    def test_critical_tier_gets_all(self, sample_alerts):
        filtered = filter_by_tier(sample_alerts, "critical")
        assert len(filtered) == 3

    def test_standard_tier_excludes_info(self, sample_alerts):
        filtered = filter_by_tier(sample_alerts, "standard")
        assert len(filtered) == 2
        assert all(a.severity in ("critical", "warning") for a in filtered)

    def test_low_tier_only_critical(self, sample_alerts):
        filtered = filter_by_tier(sample_alerts, "low")
        assert len(filtered) == 1
        assert filtered[0].severity == "critical"

    def test_unknown_tier_returns_all(self, sample_alerts):
        filtered = filter_by_tier(sample_alerts, "unknown")
        assert len(filtered) == 3


class TestWritePrometheusYaml:
    def test_writes_grouped_yaml(self, tmp_path):
        alerts = [
            AlertRule(
                name="pg_down", severity="critical", expr="pg_up == 0", technology="postgresql"
            ),
            AlertRule(
                name="redis_down", severity="critical", expr="redis_up == 0", technology="redis"
            ),
        ]
        output_file = tmp_path / "alerts.yaml"
        write_prometheus_yaml(alerts, output_file, "checkout")

        content = output_file.read_text()
        assert "# Alert rules generated by NthLayer" in content

        # Parse the YAML (skip comment header)
        yaml_content = "\n".join(line for line in content.split("\n") if not line.startswith("#"))
        data = yaml.safe_load(yaml_content)
        assert "groups" in data
        group_names = [g["name"] for g in data["groups"]]
        assert "checkout-postgresql" in group_names
        assert "checkout-redis" in group_names

    def test_creates_parent_dirs(self, tmp_path):
        alerts = [AlertRule(name="test", severity="critical", expr="up==0", technology="test")]
        output_file = tmp_path / "sub" / "dir" / "alerts.yaml"
        write_prometheus_yaml(alerts, output_file, "svc")
        assert output_file.exists()


class TestGenerateAlertsForService:
    def test_with_example_service(self):
        """Generate alerts from example checkout-service.yaml."""
        service_file = Path("examples/services/checkout-service.yaml")
        if not service_file.exists():
            pytest.skip("Example service file not found")

        alerts = generate_alerts_for_service(service_file, quiet=True)
        # Should return a list (may be empty if no deps in example)
        assert isinstance(alerts, list)
