"""
Alertmanager configuration generator.

Generates Alertmanager configuration with PagerDuty receivers
and routing rules based on service definitions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class PagerDutyReceiver:
    """PagerDuty receiver configuration."""

    service_key: str  # Integration key from PagerDuty
    severity: str = "error"  # PagerDuty severity
    class_: str = ""  # Alert class
    component: str = ""  # Component that generated the alert
    group: str = ""  # Logical grouping
    send_resolved: bool = True
    url: str = "https://events.pagerduty.com/v2/enqueue"

    def to_dict(self) -> dict[str, Any]:
        """Convert to Alertmanager config format."""
        config: dict[str, Any] = {
            "service_key": self.service_key,
            "send_resolved": self.send_resolved,
        }
        if self.url != "https://events.pagerduty.com/v2/enqueue":
            config["url"] = self.url
        if self.severity:
            config["severity"] = self.severity
        if self.class_:
            config["class"] = self.class_
        if self.component:
            config["component"] = self.component
        if self.group:
            config["group"] = self.group
        return config


@dataclass
class Receiver:
    """Alertmanager receiver configuration."""

    name: str
    pagerduty_configs: list[PagerDutyReceiver] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert to Alertmanager config format."""
        result: dict[str, Any] = {"name": self.name}
        if self.pagerduty_configs:
            result["pagerduty_configs"] = [pd.to_dict() for pd in self.pagerduty_configs]
        return result


@dataclass
class Route:
    """Alertmanager routing rule."""

    receiver: str
    group_by: list[str] = field(default_factory=lambda: ["alertname", "service"])
    group_wait: str = "30s"
    group_interval: str = "5m"
    repeat_interval: str = "4h"
    matchers: list[str] = field(default_factory=list)
    routes: list[Route] = field(default_factory=list)
    continue_: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Convert to Alertmanager config format."""
        result: dict[str, Any] = {"receiver": self.receiver}
        if self.group_by:
            result["group_by"] = self.group_by
        if self.group_wait:
            result["group_wait"] = self.group_wait
        if self.group_interval:
            result["group_interval"] = self.group_interval
        if self.repeat_interval:
            result["repeat_interval"] = self.repeat_interval
        if self.matchers:
            result["matchers"] = self.matchers
        if self.routes:
            result["routes"] = [r.to_dict() for r in self.routes]
        if self.continue_:
            result["continue"] = True
        return result


@dataclass
class InhibitRule:
    """Alertmanager inhibition rule."""

    source_matchers: list[str] = field(default_factory=list)
    target_matchers: list[str] = field(default_factory=list)
    equal: list[str] = field(default_factory=lambda: ["alertname", "service"])

    def to_dict(self) -> dict[str, Any]:
        """Convert to Alertmanager config format."""
        return {
            "source_matchers": self.source_matchers,
            "target_matchers": self.target_matchers,
            "equal": self.equal,
        }


@dataclass
class AlertmanagerConfig:
    """Complete Alertmanager configuration."""

    route: Route
    receivers: list[Receiver] = field(default_factory=list)
    inhibit_rules: list[InhibitRule] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert to Alertmanager config format."""
        return {
            "route": self.route.to_dict(),
            "receivers": [r.to_dict() for r in self.receivers],
            "inhibit_rules": [ir.to_dict() for ir in self.inhibit_rules],
        }

    def to_yaml(self) -> str:
        """Convert to YAML string."""
        return yaml.dump(self.to_dict(), default_flow_style=False, sort_keys=False)

    def write(self, path: Path) -> None:
        """Write configuration to file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write("# Alertmanager configuration generated by NthLayer\n")
            f.write("# Do not edit manually - regenerate with: nthlayer apply\n\n")
            f.write(self.to_yaml())


def generate_alertmanager_config(
    service_name: str,
    team: str,
    pagerduty_integration_key: str,
    support_model: str = "self",
    tier: str = "medium",
    sre_integration_key: str | None = None,
) -> AlertmanagerConfig:
    """
    Generate Alertmanager configuration for a service.

    Args:
        service_name: Name of the service
        team: Team owning the service
        pagerduty_integration_key: PagerDuty Events API v2 integration key
        support_model: Support model (self, shared, sre, business_hours)
        tier: Service tier (critical, high, medium, low)
        sre_integration_key: Optional SRE PagerDuty integration key for routing

    Returns:
        AlertmanagerConfig with receivers and routes
    """
    receivers: list[Receiver] = []
    routes: list[Route] = []

    # Create team receiver
    team_receiver = Receiver(
        name=f"{team}-pagerduty",
        pagerduty_configs=[
            PagerDutyReceiver(
                service_key=pagerduty_integration_key,
                severity=_tier_to_severity(tier),
                component=service_name,
                group=team,
            )
        ],
    )
    receivers.append(team_receiver)

    # Create SRE receiver if integration key provided
    if sre_integration_key:
        sre_receiver = Receiver(
            name="sre-pagerduty",
            pagerduty_configs=[
                PagerDutyReceiver(
                    service_key=sre_integration_key,
                    severity="critical",
                    component=service_name,
                    group="sre",
                )
            ],
        )
        receivers.append(sre_receiver)

        # Add route for SRE routing label
        sre_route = Route(
            receiver="sre-pagerduty",
            matchers=['routing="sre"'],
            group_by=["alertname", "service"],
        )
        routes.append(sre_route)

    # Create default route to team
    default_route = Route(
        receiver=f"{team}-pagerduty",
        matchers=[f'service="{service_name}"'],
        group_by=["alertname", "service"],
        group_wait=_tier_to_group_wait(tier),
        repeat_interval=_tier_to_repeat_interval(tier),
    )
    routes.append(default_route)

    # Create root route
    root_route = Route(
        receiver=f"{team}-pagerduty",
        group_by=["alertname", "service"],
        routes=routes,
    )

    # Create inhibit rules
    inhibit_rules = [
        # Critical inhibits warning for same alert
        InhibitRule(
            source_matchers=['severity="critical"'],
            target_matchers=['severity="warning"'],
            equal=["alertname", "service"],
        ),
    ]

    return AlertmanagerConfig(
        route=root_route,
        receivers=receivers,
        inhibit_rules=inhibit_rules,
    )


def _tier_to_severity(tier: str) -> str:
    """Map service tier to PagerDuty severity."""
    return {
        "critical": "critical",
        "high": "error",
        "medium": "warning",
        "low": "info",
    }.get(tier.lower(), "warning")


def _tier_to_group_wait(tier: str) -> str:
    """Map service tier to group wait time."""
    return {
        "critical": "10s",
        "high": "30s",
        "medium": "1m",
        "low": "5m",
    }.get(tier.lower(), "30s")


def _tier_to_repeat_interval(tier: str) -> str:
    """Map service tier to repeat interval."""
    return {
        "critical": "1h",
        "high": "2h",
        "medium": "4h",
        "low": "12h",
    }.get(tier.lower(), "4h")
