"""CLI command for migrating srm/v1 manifests to opensrm.nthlayer.io/v2.

Usage::

    nthlayer migrate-manifest service.yaml
    nthlayer migrate-manifest service.yaml --output service.v2.yaml
    nthlayer migrate-manifest service.yaml --dry-run

Acceptance (opensrm-b22.2): converts every demo spec; output round-trips
through the v2 parser without loss of canonical fields.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

from nthlayer_common.manifest.parser.v2 import OpenSRMV2ParseError, parse_opensrm_v2
from nthlayer_common.manifest.v1_compat import convert_v1_to_v2

from nthlayer_generate.cli.ux import console, error, header, success


def register_migrate_manifest_parser(
    subparsers: argparse._SubParsersAction[Any],
) -> None:
    """Register the migrate-manifest command parser."""
    p = subparsers.add_parser(
        "migrate-manifest",
        help="Migrate an srm/v1 manifest to opensrm.nthlayer.io/v2",
    )
    p.add_argument("manifest", help="Path to srm/v1 manifest YAML")
    p.add_argument(
        "--output",
        "-o",
        help="Output path for the v2 manifest (default: alongside input as *.v2.yaml)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the v2 YAML to stdout without writing a file",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing output file",
    )


def handle_migrate_manifest_command(args: argparse.Namespace) -> int:
    return migrate_manifest_command(
        manifest_path=args.manifest,
        output_path=getattr(args, "output", None),
        dry_run=getattr(args, "dry_run", False),
        force=getattr(args, "force", False),
    )


def migrate_manifest_command(
    manifest_path: str,
    output_path: str | None = None,
    dry_run: bool = False,
    force: bool = False,
) -> int:
    """Convert an srm/v1 manifest to opensrm.nthlayer.io/v2 and verify round-trip.

    Returns 0 on success, 1 on error.
    """
    in_path = Path(manifest_path)
    if not in_path.exists():
        error(f"Manifest not found: {manifest_path}")
        return 1

    try:
        with open(in_path) as f:
            v1_data = yaml.safe_load(f)
    except yaml.YAMLError as exc:
        error(f"Invalid YAML in {manifest_path}: {exc}")
        return 1

    if not isinstance(v1_data, dict):
        error(f"Manifest is not a YAML object: {manifest_path}")
        return 1

    if v1_data.get("apiVersion") == "opensrm.nthlayer.io/v2":
        success(f"{in_path.name} is already opensrm.nthlayer.io/v2 — no migration needed.")
        return 0

    try:
        v2_data = convert_v1_to_v2(v1_data)
    except ValueError as exc:
        error(f"Cannot convert {manifest_path}: {exc}")
        return 1

    # Round-trip verification: the converted manifest must parse via the
    # v2 parser. If parsing fails, the migration produced bad output —
    # surface that loudly rather than writing a broken file.
    try:
        parse_opensrm_v2(v2_data)
    except OpenSRMV2ParseError as exc:
        error(f"Converted manifest fails v2 parse: {exc}")
        return 1

    yaml_text = (
        "# OpenSRM v2 manifest (migrated from srm/v1)\n"
        f"# Source: {in_path.name}\n"
        "# Generated by `nthlayer migrate-manifest`.\n\n"
        + yaml.safe_dump(v2_data, default_flow_style=False, sort_keys=False)
    )

    if dry_run:
        header(f"Migration preview: {in_path.name}")
        console.print()
        print(yaml_text)
        return 0

    out_path = Path(output_path) if output_path else in_path.with_suffix(".v2.yaml")
    if out_path.exists() and not force:
        error(f"Output file exists: {out_path} — use --force to overwrite")
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml_text)

    success(f"Migrated {in_path.name} → {out_path}")
    return 0
